// Fun baby gift items for the shopping phase
const BABY_ITEMS = [
    { id: 'sunglasses', emoji: '😎', name: 'Tiny Sunglasses', desc: 'Born cool' },
    { id: 'dj-headphones', emoji: '🎧', name: 'Baby DJ Headphones', desc: 'Drop beats, not bottles' },
    { id: 'ceo-bib', emoji: '👔', name: '"Future CEO" Bib', desc: 'Drool in style' },
    { id: 'rubber-ducks', emoji: '🦆', name: 'Rubber Duck Army', desc: 'Squad goals' },
    { id: 'mini-sneakers', emoji: '👟', name: 'Mini Sneakers', desc: 'Fastest crawler in town' },
    { id: 'cricket-bat', emoji: '🏏', name: 'Baby Cricket Bat', desc: 'IPL 2045 draft pick' },
    { id: 'dino-plush', emoji: '🦕', name: 'Giant Dino Plush', desc: 'Bigger than the baby' },
    { id: 'sleep-sub', emoji: '😴', name: 'Sleep Subscription', desc: 'For the parents, obviously' },
    { id: 'noise-machine', emoji: '🔇', name: 'Noise Canceller', desc: 'For the neighbours' },
    { id: 'cape', emoji: '🦸', name: 'Baby Cape', desc: 'Superhero origin story' },
    { id: 'tiny-throne', emoji: '🪑', name: 'Tiny Throne', desc: 'Every royal needs one' },
    { id: 'passport', emoji: '✈️', name: 'Baby Passport', desc: 'World traveler from day 1' },
    { id: 'drumkit', emoji: '🥁', name: 'Mini Drum Kit', desc: 'Sorry, neighbours' },
    { id: 'cookbook', emoji: '📖', name: '"Cooking for Chaos" Book', desc: 'One-handed recipes' },
    { id: 'roomba', emoji: '🤖', name: 'Baby Roomba', desc: 'Cleans up their own mess' },
    { id: 'crown', emoji: '👑', name: 'Royal Crown', desc: 'Because obviously' },
    { id: 'stocks', emoji: '📈', name: 'First Stock Portfolio', desc: 'Start compounding early' },
    { id: 'camera', emoji: '📸', name: 'Baby Vlog Camera', desc: 'Content creator from birth' },
    { id: 'hammock', emoji: '🏖️', name: 'Mini Hammock', desc: 'Retirement starts at 0' },
    { id: 'espresso', emoji: '☕', name: 'Espresso Machine', desc: 'For the parents. Survival kit.' },
    { id: 'disco-ball', emoji: '🪩', name: 'Nursery Disco Ball', desc: '3 AM dance parties' },
    { id: 'megaphone', emoji: '📣', name: 'Tiny Megaphone', desc: 'As if they need help being loud' },
    { id: 'trophy', emoji: '🏆', name: '"Best Baby" Trophy', desc: 'Won before arriving' },
    { id: 'jetpack', emoji: '🚀', name: 'Baby Jetpack', desc: 'Crawling is for amateurs' },
    { id: 'plant', emoji: '🌱', name: 'First Plant Baby', desc: 'Practice nurturing' },
];
