// Fun baby gift items for the shopping phase (55+ items, each player sees random 20)
const BABY_ITEMS = [
    { id: 'sunglasses', emoji: '😎', name: 'Tiny Sunglasses', desc: 'Born cool' },
    { id: 'dj-headphones', emoji: '🎧', name: 'Baby DJ Headphones', desc: 'Drop beats, not bottles' },
    { id: 'ceo-bib', emoji: '👔', name: '"Future CEO" Bib', desc: 'Drool in style' },
    { id: 'rubber-ducks', emoji: '🦆', name: 'Rubber Duck Army', desc: 'Squad goals' },
    { id: 'mini-sneakers', emoji: '👟', name: 'Mini Sneakers', desc: 'Fastest crawler in town' },
    { id: 'cricket-bat', emoji: '🏏', name: 'Baby Cricket Bat', desc: 'IPL 2045 draft pick' },
    { id: 'dino-plush', emoji: '🦕', name: 'Giant Dino Plush', desc: 'Bigger than the baby' },
    { id: 'sleep-sub', emoji: '😴', name: 'Sleep Subscription', desc: 'For the parents, obviously' },
    { id: 'noise-machine', emoji: '🔇', name: 'Noise Canceller', desc: 'For the neighbours' },
    { id: 'cape', emoji: '🦸', name: 'Baby Cape', desc: 'Superhero origin story' },
    { id: 'tiny-throne', emoji: '🪑', name: 'Tiny Throne', desc: 'Every royal needs one' },
    { id: 'passport', emoji: '✈️', name: 'Baby Passport', desc: 'World traveler from day 1' },
    { id: 'drumkit', emoji: '🥁', name: 'Mini Drum Kit', desc: 'Sorry, neighbours' },
    { id: 'cookbook', emoji: '📖', name: '"Cooking for Chaos" Book', desc: 'One-handed recipes' },
    { id: 'roomba', emoji: '🤖', name: 'Baby Roomba', desc: 'Cleans up their own mess' },
    { id: 'crown', emoji: '👑', name: 'Royal Crown', desc: 'Because obviously' },
    { id: 'stocks', emoji: '📈', name: 'First Stock Portfolio', desc: 'Start compounding early' },
    { id: 'camera', emoji: '📸', name: 'Baby Vlog Camera', desc: 'Content creator from birth' },
    { id: 'hammock', emoji: '🏖️', name: 'Mini Hammock', desc: 'Retirement starts at 0' },
    { id: 'espresso', emoji: '☕', name: 'Espresso Machine', desc: 'For the parents. Survival kit.' },
    { id: 'disco-ball', emoji: '🪩', name: 'Nursery Disco Ball', desc: '3 AM dance parties' },
    { id: 'megaphone', emoji: '📣', name: 'Tiny Megaphone', desc: 'As if they need help being loud' },
    { id: 'trophy', emoji: '🏆', name: '"Best Baby" Trophy', desc: 'Won before arriving' },
    { id: 'jetpack', emoji: '🚀', name: 'Baby Jetpack', desc: 'Crawling is for amateurs' },
    { id: 'plant', emoji: '🌱', name: 'First Plant Baby', desc: 'Practice nurturing' },
    { id: 'ukulele', emoji: '🎸', name: 'Mini Ukulele', desc: 'Tiny musician energy' },
    { id: 'star-projector', emoji: '🌟', name: 'Star Projector', desc: 'Galaxy ceiling at bedtime' },
    { id: 'bubble-machine', emoji: '🫧', name: 'Bubble Machine', desc: 'Infinite entertainment' },
    { id: 'teddy-bear', emoji: '🧸', name: 'Giant Teddy Bear', desc: 'First bestie' },
    { id: 'onesie-tux', emoji: '🤵', name: 'Tuxedo Onesie', desc: 'Formal but comfy' },
    { id: 'baby-gym', emoji: '💪', name: 'Baby Gym Set', desc: 'Gains start early' },
    { id: 'night-light', emoji: '🌙', name: 'Moon Night Light', desc: 'Sweet dreams guaranteed' },
    { id: 'stroller-f1', emoji: '🏎️', name: 'F1 Stroller', desc: 'Box box box!' },
    { id: 'blankie', emoji: '🧶', name: 'Cloud-Soft Blankie', desc: 'Maximum snuggles' },
    { id: 'art-kit', emoji: '🎨', name: 'Baby Art Kit', desc: 'Future Picasso loading' },
    { id: 'binoculars', emoji: '🔭', name: 'Tiny Binoculars', desc: 'Bird watcher in training' },
    { id: 'chef-hat', emoji: '👨‍🍳', name: 'Mini Chef Hat', desc: 'Kitchen disasters await' },
    { id: 'globe', emoji: '🌍', name: 'World Globe', desc: 'So many places to drool on' },
    { id: 'pilot-goggles', emoji: '🥽', name: 'Pilot Goggles', desc: 'Ready for takeoff' },
    { id: 'soccer-ball', emoji: '⚽', name: 'Tiny Soccer Ball', desc: 'World Cup 2050 starter' },
    { id: 'bow-tie', emoji: '🎀', name: 'Fancy Bow Tie', desc: 'Dapper from day one' },
    { id: 'magic-wand', emoji: '🪄', name: 'Magic Wand', desc: 'Abracada-baby!' },
    { id: 'treasure-map', emoji: '🗺️', name: 'Treasure Map', desc: 'Adventure awaits' },
    { id: 'sippy-cup', emoji: '🥤', name: 'Golden Sippy Cup', desc: 'Hydration in luxury' },
    { id: 'panda-suit', emoji: '🐼', name: 'Panda Onesie', desc: 'Unbearably cute' },
    { id: 'safari-hat', emoji: '🤠', name: 'Safari Hat', desc: 'Explorer mode: ON' },
    { id: 'fairy-wings', emoji: '🧚', name: 'Fairy Wings', desc: 'Float through naptime' },
    { id: 'boombox', emoji: '📻', name: 'Nursery Boombox', desc: 'Lullaby remix edition' },
    { id: 'telescope', emoji: '🔭', name: 'Baby Telescope', desc: 'Reaching for the stars' },
    { id: 'skateboard', emoji: '🛹', name: 'Mini Skateboard', desc: 'Gnarly little dude' },
    { id: 'tiara', emoji: '👸', name: 'Sparkle Tiara', desc: 'Royal from birth' },
    { id: 'walkie-talkie', emoji: '📱', name: 'Walkie-Talkies', desc: 'Baby-to-base comms' },
    { id: 'garden-set', emoji: '🌻', name: 'Garden Starter Set', desc: 'Grow something besides mess' },
    { id: 'train-set', emoji: '🚂', name: 'Toy Train Set', desc: 'Choo choo, all aboard!' },
    { id: 'bath-toys', emoji: '🐠', name: 'Ocean Bath Toys', desc: 'Splish splash squad' },
    { id: 'piggy-bank', emoji: '🐷', name: 'Piggy Bank', desc: 'Saving for college already' },
];
